import { describe, expect, it } from 'vitest';
import { offendingLines, sourceFiles } from '$lib/test/source-scan';

/**
 * The host is swappable, and nothing above the boundary may name it
 * (AR-DEPLOY-5).
 *
 * AR-TRANSPORT-10's provider-neutrality rule, applied to hosting. Its tag read
 * "vacuously satisfied — no `platform.env` usage anywhere — but no boundary
 * module enforces it", and vacuous satisfaction is precisely the state that ends
 * quietly: the first person who needs a KV namespace reaches for
 * `platform.env` because that is what the Workers documentation shows, and the
 * named fallback (a plain Node server) becomes an audit instead of a swap.
 *
 * AMENDS THE REQUIREMENT, which asks for Workers concepts to "live behind a
 * boundary". **The boundary already exists and is not a module of ours**: it is
 * SvelteKit's `$env/dynamic/private`, which hands the control plane an
 * environment without saying who provides it — see
 * [supabase-admin.ts](./supabase-admin.ts), whose comment already explains why
 * runtime env is read that way (the secret must not enter a build artifact,
 * AR-DEPLOY-6). Writing a wrapper module around it to satisfy the letter of the
 * requirement would add a file that forwards one call and enforces nothing;
 * what actually enforces the rule is this test.
 *
 * So the requirement is met by a DIFFERENT mechanism than its text describes,
 * and that is recorded in DESIGN.md rather than quietly ticked — the same
 * treatment AR-COST-6's lazy weekly roll got.
 */

/**
 * Host-specific vocabulary.
 *
 * `platform.env` is the Workers-shaped door SvelteKit offers, and the one the
 * requirement names. The rest are the bindings that would arrive through it:
 * KV, Durable Objects, R2, D1, and the Cloudflare-specific request property.
 *
 * The word "Cloudflare" alone is deliberately NOT banned. It appears in prose
 * and in `wrangler.jsonc`, and comments are stripped before this runs anyway;
 * banning the vendor's name rather than its BINDINGS would catch documentation
 * and miss `env.MY_KV`.
 */
const HOST_BINDINGS =
	/\bplatform\.env\b|\bKVNamespace\b|\bDurableObject\w*\b|\bR2Bucket\b|\bD1Database\b|\bFetcher\b|\bcf\.colo\b/;

describe('nothing above the boundary names the host (AR-DEPLOY-5)', () => {
	const files = sourceFiles({
		exempt: (relative) =>
			// This file names them in order to ban them.
			relative === 'lib/server/no-host-bindings.spec.ts' ||
			// Generated by `wrangler types`, and enormous. It describes the
			// platform's own surface rather than using it, which is the
			// distinction this rule cares about.
			relative === 'worker-configuration.d.ts'
	});

	it('finds source files to check', () => {
		expect(files.length).toBeGreaterThan(50);
	});

	it.each(files.map((f) => [f.relative, f] as const))('%s names no host binding', (_relative, file) => {
		expect(offendingLines(file, HOST_BINDINGS)).toEqual([]);
	});

	it('the boundary the control plane actually uses is the env module', () => {
		// The positive half of the claim: there IS a single sanctioned way to
		// reach the runtime environment, and it is host-neutral. A rule that only
		// forbids leaves the next person with nowhere to go.
		const [admin, ...rest] = sourceFiles({
			exempt: (relative) => relative !== 'lib/server/supabase-admin.ts'
		});
		expect(rest).toEqual([]);
		expect(admin).toBeDefined();
		if (admin === undefined) return;
		expect(offendingLines(admin, /\$env\/dynamic\/private/)).not.toEqual([]);
	});

	it('the pattern actually matches what it claims to', () => {
		// The guard on the guard.
		expect(HOST_BINDINGS.test('const kv = platform.env.SESSIONS;')).toBe(true);
		expect(HOST_BINDINGS.test('let ns: KVNamespace;')).toBe(true);
		expect(HOST_BINDINGS.test('export class Room implements DurableObject {}')).toBe(true);
		// The neutral path stays legal.
		expect(HOST_BINDINGS.test("import { env } from '$env/dynamic/private';")).toBe(false);
	});
});
